### ISSUE TITLE
Todo App 구현

### ISSUE THREAD

**Issue by gyeongseo944** [gyeongseo944/HelloToday#1]
##만들고자 하는 기능
- Notion 오픈 API를 이용한 Todo 의 CRUD 구현 

##구현 To do 
1. [x] Todo 생성시 notion에 새로운 todo 생성 
2. [x] notion에 있는 todo list 가져오기 >> Category 별로 Todolist 확인 가능
3. [x] Todo 할 일 체크 시 notion 의 complete 속성 변화 , list 에서 바로 확인 가능
4. [x] Todo의 휴지통 아이콘 클릭시 notion todo list 에서 삭제
